version: '3.8'
services:
  atlantis:
    image: ghcr.io/runatlantis/atlantis:v0.24.3
    container_name: atlantis
    ports:
      - "4141:4141"
    environment:
      - ATLANTIS_GH_USER=${ATLANTIS_GH_USER}
      - ATLANTIS_GH_TOKEN=${ATLANTIS_GH_TOKEN}
      - ATLANTIS_GH_WEBHOOK_SECRET=${ATLANTIS_GH_WEBHOOK_SECRET}
      - ATLANTIS_REPO_ALLOWLIST=github.com/sanju-naik72/*
    volumes:
      - ./:/atlantis-data
    command:
      - atlantis
      - server
      - --atlantis-url=http://localhost:4141
      - --repo-allowlist=github.com/sanju-naik72/*
      - --repo-config=/atlantis-data/atlantis.yaml